stages:
  - test
  - release
  - deploy

test_photographer:
  stage: test
  image: $CI_REGISTRY/$CI_PROJECT_PATH/photoapptest
  script:
  - cd app/photographer-service
  - pytest -v -p no:warnings
  services:
    - name: mongo:4.4-rc
      alias: mongo-service-test

test_photo:
  stage: test
  image: $CI_REGISTRY/$CI_PROJECT_PATH/photoapptest
  script:
  - cd app/photo-service
  - pytest -v -p no:warnings
  services:
    - name: mongo:4.4-rc
      alias: mongo-service-test
    - name: gitlab-devops.cloud.rennes.enst-bretagne.fr:4567/devops/shared/tags:latest
      alias: tags-service-test

build_photographer:
  stage: release
  image: $CI_REGISTRY/devops/shared/docker:proxy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd app/photographer-service
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/photographer:${CI_COMMIT_SHORT_SHA} --network=host .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/photographer:${CI_COMMIT_SHORT_SHA}

build_photo:
  stage: release
  image: $CI_REGISTRY/devops/shared/docker:proxy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd app/photo-service
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/photo:${CI_COMMIT_SHORT_SHA} --network=host .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/photo:${CI_COMMIT_SHORT_SHA}

deploy_photographer:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - cd app/photographer-service
    - sed -i "s/:latest/:${CI_COMMIT_SHORT_SHA}/g" k8s-photographer-deployment.yml
    - kubectl apply -f k8s-photographer-deployment.yml
    - kubectl apply -f k8s-photographer-service.yml
  environment:
    name: production

deploy_photo:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - cd app/photo-service
    - sed -i "s/:latest/:${CI_COMMIT_SHORT_SHA}/g" k8s-photo-deployment.yml
    - kubectl apply -f k8s-photo-deployment.yml
    - kubectl apply -f k8s-photo-service.yml
  environment:
    name: production

deploy_tags:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - cd app/tags-service
    - kubectl apply -f k8s-tags-deployment.yml
    - kubectl apply -f k8s-tags-service.yml
  environment:
    name: production
