# Default values for gravitee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mongo:
  uri: mongodb://g16-user:xYyR4FPh4W79YY6vWiDm@mongo.cloud.rennes.enst-bretagne.fr/g16-gravitee-db?authSource=g16-gravitee-db
es:
  endpoints:
    - http://192.168.10.11:9200

ui:
  ingress:
    # Used to create an Ingress record.
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1$2
      nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\n"
      cert-manager.io/issuer: my-root-ca-issuer
    tls:
      - hosts:
          - apim.example.com
        secretName: api-custom-cert

api:
  ingress:
    management:
      enabled: true
      path: /management
      # Used to create an Ingress record.
      hosts:
        - apim.example.com
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\nproxy_set_header if-match \"\";\n"
        cert-manager.io/issuer: my-root-ca-issuer
        # kubernetes.io/tls-acme: "true"
      #tls:
        # Secrets must be manually created in the namespace.
        # - secretName: chart-example-tls
        #   hosts:
        #     - chart-example.local
      tls:
        - hosts:
            - apim.example.com
          secretName: api-custom-cert
    portal:
      enabled: true
      path: /portal
      # Used to create an Ingress record.
      hosts:
        - apim.example.com
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\nproxy_set_header if-match \"\";\n"
        cert-manager.io/issuer: my-root-ca-issuer
        # kubernetes.io/tls-acme: "true"
      #tls:
        # Secrets must be manually created in the namespace.
        # - secretName: chart-example-tls
        #   hosts:
        #     - chart-example.local
      tls:
        - hosts:
            - apim.example.com
          secretName: api-custom-cert

gateway:
  image:
    repository: graviteeio/apim-gateway
    tag: 3.7.0
  resources:
    limits:
      cpu: 500m
      memory: 750Mi
  ingress:
    enabled: true
    path: /gateway
    # Used to create an Ingress record.
    hosts:
      - apim.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/issuer: my-root-ca-issuer
      # nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\nproxy_set_header if-match \"\";\n"
      # kubernetes.io/tls-acme: "true"
    #tls:
      # Secrets must be manually created in the namespace.
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
    tls:
      - hosts:
          - apim.example.com
        secretName: api-custom-cert

portal:
  ingress:
    enabled: true
    path: /
    # Used to create an Ingress record.
    hosts:
      - apim.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\n"
      cert-manager.io/issuer: my-root-ca-issuer
      #tls:
      # Secrets must be manually created in the namespace.
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
    tls:
      - hosts:
          - apim.example.com
        secretName: api-custom-cert
