apiVersion: v1
kind: Service
metadata:
  name: photo-service
spec:
  type: NodePort
  ports:
  - port: 50051
    protocol: TCP
    nodePort: 30302
    targetPort: 50051
  selector:
    app: photo-service