heat_template_version: rocky

description: Template with monitoring server

parameters:
  ssh_keys:
    type: comma_delimited_list

resources:
  monitoring_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.4

  monitoring:
    type: vm-template.yaml
    properties:
      name: monitoring
      flavor: s10.medium
      network_port: { get_resource: monitoring_port}
      ssh_keys: {get_param: ssh_keys}