heat_template_version: rocky

description: Template with 6 kubernetes nodes

parameters:
  ssh_keys:
    type: comma_delimited_list

resources:
  kubernetes_port_1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.5

  kubernetes_node_1:
    type: vm-template.yaml
    properties:
      name: node_1
      flavor: s10.medium
      network_port: { get_resource: kubernetes_port_1}
      ssh_keys: {get_param: ssh_keys}

  kubernetes_port_2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.6

  kubernetes_node_2:
    type: vm-template.yaml
    properties:
      name: node_2
      flavor: s10.medium
      network_port: { get_resource: kubernetes_port_2}
      ssh_keys: {get_param: ssh_keys}

  kubernetes_port_3:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.7

  kubernetes_node_3:
    type: vm-template.yaml
    properties:
      name: node_3
      flavor: s10.medium
      network_port: { get_resource: kubernetes_port_3}
      ssh_keys: {get_param: ssh_keys}

  kubernetes_port_4:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.8

  kubernetes_node_4:
    type: vm-template.yaml
    properties:
      name: node_4
      flavor: s10.medium
      network_port: { get_resource: kubernetes_port_4}
      ssh_keys: {get_param: ssh_keys}

  kubernetes_port_5:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.9

  kubernetes_node_5:
    type: vm-template.yaml
    properties:
      name: node_5
      flavor: s10.medium
      network_port: { get_resource: kubernetes_port_5}
      ssh_keys: {get_param: ssh_keys}

  kubernetes_port_6:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.10

  kubernetes_node_6:
    type: vm-template.yaml
    properties:
      name: node_6
      flavor: s10.medium
      network_port: { get_resource: kubernetes_port_6}
      ssh_keys: {get_param: ssh_keys}