---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
      environment:
          https_proxy: http://proxy.rennes.enst-bretagne.fr:3128
          http_proxy: http://proxy.rennes.enst-bretagne.fr:3128

    - name: Import the public key used by the package management system
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      environment:
          https_proxy: http://proxy.rennes.enst-bretagne.fr:3128
          http_proxy: http://proxy.rennes.enst-bretagne.fr:3128

    - name: Add repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present  

    - name: install docker
      apt:
        pkg: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
      environment:
          https_proxy: http://proxy.rennes.enst-bretagne.fr:3128
          http_proxy: http://proxy.rennes.enst-bretagne.fr:3128

    - name: modify groups
      shell: usermod -aG docker $USER
      notify:
        - start docker

    - name: add line to docker config file
      lineinfile:
        path: /lib/systemd/system/docker.service
        state: present
        line: Environment="HTTP_PROXY=http://proxy.rennes.enst-bretagne.fr:3128" "HTTPS_PROXY=http://proxy.rennes.enst-bretagne.fr:3128" "NO_PROXY=gitlab-devops.cloud.rennes.enst-bretagne.fr:4567"
      notify:
        - restart docker

    # the last task did not abled us to do docker pull from public repository
    # so we follow this instructions https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy
    - name: Creating a new directory for the config
      file:
        path: "/etc/systemd/system/docker.service.d"
        state: directory
    - name: Creating the config file
      file:
        path: "/etc/systemd/system/docker.service.d/http-proxy.conf"
        state: touch
    - name: Create http config for docker
      copy:
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
        content: |
        [Service]
        Environment="HTTP_PROXY=http://proxy.rennes.enst-bretagne.fr:3128"
        Environment="HTTPS_PROXY=http://proxy.rennes.enst-bretagne.fr:3128"
        Environment="NO_PROXY=gitlab-devops.cloud.rennes.enst-bretagne.fr:4567"
      notify:
        - daemon-reload
        - restart docker
    # finish with https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

    - name: download CA
      get_url:
        url: http://www.cloud.rennes.enst-bretagne.fr/files/docker-lab/root-ca.crt
        dest: /usr/local/share/ca-certificates/root-ca.crt

    - name: update certificates
      shell: update-ca-certificates

    - name: reboot VM
      reboot:
      notify:
        - start docker

    # after this manually do
    # sudo docker login gitlab-devops.cloud.rennes.enst-bretagne.fr:4567
    # sudo docker pull gitlab-devops.cloud.rennes.enst-bretagne.fr:4567/t19hadda/202102_devops-s21-16/ws

  handlers:
  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes
  - name: restart docker
    service:
      name: docker
      state: restarted
  - name: reload systemd
    command: systemctl daemon-reload
