apiVersion: v1
kind: Service
metadata:
  name: photographer-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30300
    targetPort: 80
  selector:
    app: photographer-service