apiVersion: v1
kind: Pod
metadata:
  name: test-webserver
spec:
  containers:
  - name: test-webserver
    image: gitlab-devops.cloud.rennes.enst-bretagne.fr:4567/t19hadda/202102_devops-s21-16/k8s_test
    ports:
    - containerPort: 8000
  imagePullSecrets:
  - name: regcred
